name: Linter CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Install dependencies
            run: make
          - run: make install
          - run: make lint
          - run: make test
